[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "glimmer"
version = "0.3"
authors = [
    {name = "Immanuel Weber", email = "immanuel.weber@gmail.com"}
]
description = "glimmer utilities library"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20",
    "pandas>=1.3",
    "matplotlib>=3.4",
    "ipython>=7.0",
    "torch>=1.11",
    "pytorch-lightning>=1.6",
]

[tool.setuptools.packages.find]
# Automatically discovers packages
