name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import glimmer
        2. Call function X with parameters Y
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Expected the function to return...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, it raised...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: Please provide a minimal code example that reproduces the issue
      placeholder: |
        ```python
        import glimmer
        # Your code here
        ```
      render: python

  - type: input
    id: version
    attributes:
      label: Glimmer Version
      description: What version of glimmer are you using?
      placeholder: e.g., 0.3.0
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., 3.10.5
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      placeholder: e.g., Ubuntu 22.04, macOS 13.0, Windows 11

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (e.g., error messages, logs)
      placeholder: Full error traceback, logs, screenshots...
