blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/immanuelweber/glimmer-utils/blob/main/README.md
    about: Check out the README for usage instructions and examples
  - name: PyPI Package
    url: https://pypi.org/project/glimmer/
    about: View the package on PyPI
